### PR TITLE
Full revamp of sign language classification + references

### PR DESCRIPTION
**Pull request by d97hah**
NB: glottolog-admin check gives errors which I believe are a bug **hh:h:Test:ref(**) should be legal.

### CODE REVIEW

**Comment by d97hah** [comment]
!!hh:h:Test:Ref(!!) should be legal (replace ! with asterisk)

**Comment by xrotwang** [comment]
@d97hah the problematic issue seem to be seemingly misapplied braces, e.g.
```
... and ASL in **hh:h:Bickford:EEurope(**):40-41, the specific study relayed in **hh:typ:Hollman:Estonian-Sign(**):42-43
```
There seem to be 77 such cases:
```
$ grep -r "(\*\*)" languoids/ | wc -l
77
```
Should I fix? It looks as if no braces are wanted in these cases.

**Comment by xrotwang** [comment]
@d97hah I have a fixed version locally now. Let me know if I should push.

**Comment by d97hah** [comment]
No, that's our official syntax for rendering the parenthesis only around
the year when the citation is expanded, i.e., **h:Bickford:EEurope(**)
should yield Bickford (2009) and  **h:Bickford:EEurope** should
yield Bickford 2009.

Pada Rab, 6 Mar 2024 pukul 13.55 Robert Forkel ***@***.***>
menulis:

**Comment by xrotwang** [comment]
Ok, I'll check whether I can hack that in. I dunno whether it was official, but it wasn't used so far :)

**Comment by xrotwang** [comment]
The corresponding lines in `subrefs`, e.g.
```
[classification]
sub = Arguments for the independent development of TID from the 16th century is given in **hh:ssoc:Zeshan:Turk-Isaret(**):238-252.
subrefs = 
    **hh:ssoc:Zeshan:Turk-Isaret(**
```
look wrong, though.

**Comment by xrotwang** [comment]
What about `**key**()` as new, official syntax? That way, the syntax for formatting would only be part of the text and not of the list?

**Comment by d97hah** [comment]
Hi!
1. Yes the cases like

subrefs =
    **hh:ssoc:Zeshan:Turk-Isaret(**

were errors (though I had gotten rid of them but hadn't, now newest
push should have gotten them right)

2. It's correct that the () syntax wasn't used so far, but I looked
into it not too long ago and concluded it was official :-)

3. "What about **key**() as new, official syntax? That way, the syntax
for formatting would only be part of the text and not of the list?"

The ():s indeed shouldn't be in the list, my error, now fixed,
removing the impetus for a syntax change

I'm all done with updates now, so feel free to go ahead with 5.0




Pada Rab, 6 Mar 2024 pukul 15.30 Robert Forkel ***@***.***>
menulis:

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
