### PR TITLE
add missing south3123 iso retirement remedy

### PR DESCRIPTION
**Pull request by xflr6**
- https://iso639-3.sil.org/request/2022-006
- https://github.com/glottolog/treedb/blob/d28df8b10c29f0c69efab13c671205b094b2ff89/treedb/models.py#L1129

### CODE REVIEW

**Comment by xflr6** [comment]
Hey Robert, unfortunately #968 broke loading into `treedb` because `remedy` is a requried field.

I suppose we did not run https://github.com/glottolog/glottolog/blob/da7537493270a3328fa6d93534e68586421a5260/RELEASING.md?plain=1#L41

I think we can either release a `v4.8.1` or at least tag a `v4.8-treeedb-fixes` version like we did for `v4.3` (I think that version would need to live in a branch then to set `config/publidation.ini` back to the release values), WDYT?

**Comment by xrotwang** [comment]
Hm. I'm reading the retirement info from https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Retirements.tab - and this file doesn't list `Ret_Remedy` for `ajp`. I guess this is a glitch on SIL's part - maybe caused by the ill-formatted comment

> Merged into [apc} North Levantine Arabic

(Note the non-matching braces.)

Anyway, I'm not sure we should get (even more) into the business of fixing SIL's data. So I'd rather propose dropping this check constraint.

(I did run the treedb loading command - but then fetched some more ISO updates, assuming this wouldn't hurt, because it's an automated process.)

**Comment by xrotwang** [comment]
> P.S.: unfortunately, I was on vacation when the PR review was sent, maybe we can leave more time next time or be specific about the deadline?

Will try. It's sort of difficult finding these windows in advance, though - in particular in summer.

**Comment by xrotwang** [comment]
I think this change would need to happen in `pyglottolog`, where the ISO retirements are read. Otherwise, it will be lost again when running `glottolog-admin isoretirements`.

**Comment by xflr6** [comment]
Thanks Robert.

```sql
CREATE TABLE [ISO_639-3_Retirements] (
         Id          char(3)      NOT NULL,     -- The three-letter 639-3 identifier
         Ref_Name    varchar(150) NOT NULL,     -- reference name of language
         Ret_Reason  char(1)      NOT NULL,     -- code for retirement: C (change), D (duplicate),
                                                -- N (non-existent), S (split), M (merge)
         Change_To   char(3)      NULL,         -- in the cases of C, D, and M, the identifier 
                                                -- to which all instances of this Id should be changed
         Ret_Remedy  varchar(300) NULL,         -- The instructions for updating an instance
                                                -- of the retired (split) identifier
         Effective   date         NOT NULL)     -- The date the retirement became effective
```

I think I remember the last time I scraped this, the table was missing at least one `Ret_Remedy` for `Ret_Reaon=S(plit)` (the only type of change where the field is non-redundant) , which is why I used some other source they provided which included all the remedies and so ended up including/requiring this for all change types except `N(on-existent)`: https://github.com/glottolog/treedb/blob/d28df8b10c29f0c69efab13c671205b094b2ff89/treedb/models.py#L1135.

So +1 to relax the constraint to only require it for `S(plit)`, will do. We could also drop the remedies that we have for the other change types in `tree/**/md.ini`, WDYT?

**Comment by xflr6** [comment]
Closing this in favor of https://github.com/glottolog/treedb/commit/970f0732b9cd11f91610f943a6e4cb4e266bf8da

**Comment by xrotwang** [comment]
> We could also drop the remedies that we have for the other change types in `tree/**/md.ini`, WDYT?

While `remedy` is redundant for the other retirement types, I'm still leaning towards keeping it. I think debugging problems is conceptually easier, if the `iso_retirement` info in Glottolog is as close as possible to https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Retirements.tab

**Comment by xflr6** [comment]
SG, just to make sure: I read this as `(reason = 'S') = (remedy IS NOT NULL)`

```sql
 -- The instructions for updating an instance of the retired (split) identifier
```

Currently, we use the weaker `reason != 'S' or remedy IS NOT NULL`. No strong preference :)

**Pull request closed without merging**
