### PR TITLE
normalize latitude/longitude float values to 12 decimal digits

### PR DESCRIPTION
**Pull request by xflr6**
- simplify round-tripping
- go lower? (e.g. 4-8, see [Decimal_degrees](https://en.wikipedia.org/wiki/Decimal_degrees))

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
12 d.p. latitude/longitude is accurate at scales [smaller than a micron](https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude) -- it's probably not needed for language locations :)

 5 d.p. is ~nearest meter.

**Comment by xflr6** [comment]
Thanks Simon, +1 (see also my comment above: https://en.wikipedia.org/wiki/Decimal_degrees), will update this PR with 5 digits (4 digits might also be enough).

**Comment by xflr6** [comment]
Update force-pushed, ~900 files affected, PTAL.

**Comment by xflr6** [comment]
@d97hah: happy to re-apply to an updated master in case this conflicts with some local change.

**Comment by d97hah** [comment]
What is the gain of this? By doing it we lose some of the ability to check for exact copying in other databases / list (not that that is very important, but anyway)

**Comment by xrotwang** [comment]
I think this only simpifies round-tripping, in particular when data is read and written with different software, with possibly different precision.

**Comment by d97hah** [comment]
I see but curious to know which software doesn't handle 10 decimals? (or
whatever the max # is in Glottolog)

Pada tanggal Sel, 31 Mar 2020 pukul 17.07 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@xflr6 Did you have issues round-tripping with treedb, i.e. sqlite? If not, I'd be fine with leaving things as they are, too.

**Comment by xflr6** [comment]
Thanks Harald, I did not know about that use case (an interesting one :).

The question might be whether latitude/longitude are float values or strings. The first push here with 12 digits affected only 12 files.  It mostly removed trailing zeros or long repetetive sequences, which I suspect might not round-trip with `float()` (I did pipe through `sqlite3`). Let me force-push the first version again so you can take another look. Cheers.

**Comment by xflr6** [comment]
Re-based, also fixes the order of glottolog sources for khwa1238 now.

**Comment by xrotwang** [comment]
I'll merge now, to have a baseline for Glottolog 4.2

**Pull request merged**
