### PR TITLE
North Russian dialects

### PR DESCRIPTION
**Pull request by bignavigator**
I just added the Wikipedian link to the North Russian file.
UPD: I also added Siberian and Pomor (Both are North Russian dialects) to the dialects lists. However, since I'm new to GitHub, I couldn't find any way to create a new folder: I wanted to create pomo1249 (For Pomor) and sibe1249 (For Siberian) in nort2597 (North Russian). If you know how to add new folders here, please let me know. Thanks in advance.

### CODE REVIEW

**Comment by xrotwang** [comment]
@bignavigator thank you for your contribution!

@d97hah would be the person to add Pomor and Siberian as dialects of North Russian.

Regarding the Wikipedia link: These links in Glottolog are actually retrieved (automatically) from [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page), which in turn scrapes them from Wikipedia. So we basically just relay the mapping that has been made on Wikipedia explicitly. This means that the way to add a Wikipedia link to a Glottolog languoid is adding a Glottocode to the corresponding Wikipedia page, e.g. see the "Language codes" section for [Russian](https://en.wikipedia.org/wiki/Russian_language). So unless that happens for "Northern Russian dialects", your link here will disappear after the next automatic synchronization with wikidata.

So, @bignavigator can we cose this PR, given that @d97hah will look into adding the dialects?

**Comment by bignavigator** [comment]
@xrotwang I see, let @d97hah do that.

For Pomor: https://en.wikipedia.org/wiki/Pomor_dialects

Siberian does have articles in the Russian and Ukrainian editions only, how should we handle that?

https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%B1%D0%B8%D1%80%D1%81%D0%BA%D0%B8%D0%B5_%D1%81%D1%82%D0%B0%D1%80%D0%BE%D0%B6%D0%B8%D0%BB%D1%8C%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D1%8B

**Comment by xrotwang** [comment]
@bignavigator In general, we only link from Glottolog to sites in english. But since wikipedia is arguably the most important link in terms of discovering additional information, we could add links to non-en wikipedias, too, in particular if no entry in `en.wikipedia.org` exists. This would also not conflict with the automated curation mechanism I explained above - which only curates `en.wikipedia.org` URLs.

So I'd propose you add a link to the non-en wikipedia for Siberian - as soon as it's been added to Glottolog, and try to add Glottocodes to the `en.wikipedia` pages that already exist. I have to admit that I'm not a Wikipedia contributor myself, so I don't know how difficult that is to do.

**Comment by xrotwang** [comment]
@bignavigator Just looked around on Wikipedia, but while Glottocodes seem to be editable via [`Infobox language`](https://en.wikipedia.org/wiki/Template:Infobox_language#Additional_parameters), I couldn't find these parameters when trying to edit an actual page. I tried to do this without being logged in, though, so maybe you could have more luck.

**Comment by d97hah** [comment]
Just added the North Russian dialects in q via:
https://github.com/glottolog/glottolog/pull/new/northrussian

Pada tanggal Sen, 16 Des 2019 pukul 09.15 Robert Forkel <
notifications@github.com> menulis:

**Comment by bignavigator** [comment]
Hello dear Glottologue team, I haven't reached to you for 3 years, but here's finally an English article on the Siberian dialects: [](https://en.wikipedia.org/wiki/Siberian_dialects)

**Pull request closed without merging**
