### PR TITLE
Update md.ini

### PR DESCRIPTION
**Pull request by ibdawud**
I changed it to Songhoyboro Ciine because according to a research "Kaado" is a derogatory term and very unpopular even among the speakers of this dialect. The correct term is "Songhoyboro Ciine" which is used to address this dialect even on French Wikipedia (https://fr.m.wikipedia.org/wiki/Zarma) and wikidata ( https://www.wikidata.org/entity/Q56891 )

The next link is  a research conducted in Niger on the various Southern Songhay Languages and why the word is a derogatory term(please refer to that last paragraph on Page 2.) ( http://media.corban.edu/hydra/media/files/2019/09/10/southern-songhay-silesr1999_004-1.pdf ) 

Secondly, the word "Kaado" is unpopular in Niger, the country this dialect is spoken. This is a link to the country's database of all the languages and ethnicities. It can see clearly there's nothing like "Kaado" on there but "Songhoy". ( https://www.axl.cefan.ulaval.ca/afrique/niger.htm)
Thirdly, this is a book on Google Books titled Historical Dictionary of Niger. Upon going through, you'd realize the dialect is referred to as Songhay Proper not Kaado(Scroll down to the word SONGHAY") ( https://books.google.com.gh/books?id=ArS6_nGsar4C&printsec=frontcover&dq=inauthor:%22Abdourahmane+Idrissa%22&hl=en&sa=X&ved=2ahUKEwjYjfyD6IzvAhVp8OAKHYpOCrwQ6AEwAHoECAAQAw#v=onepage&q&f=false )

Lastly, this is an article on Zarma and it can be seen clearly on the map and the labeling. The dialect Region is reffered to as Songhay Region not Kaado Region.
( https://www.djerma.nl/zarma_en/general-info/language.html )

### CODE REVIEW

**Comment by d97hah** [comment]
Thanks for this, yes, we'll change the name to Songhoyboro Ciine. (I'll
remove your PR because of some technical issues, but reinstate the name
change in a subsequent PR). all the best, H

Pada tanggal Sel, 2 Mar 2021 pukul 00.45 ibdawud <notifications@github.com>
menulis:

**Comment by ibdawud** [comment]
You are welcome. All the best

**Comment by ibdawud** [comment]
@d97hah 
Please when will the change be visible ?

I am waiting for this so that I can proceed to update the data about this dialect on English wikipedia.

**Comment by xrotwang** [comment]
The change will only be visible at https://glottolog.org after the next
release, probably within the next 3 months.

ibdawud <notifications@github.com> schrieb am Mi., 3. März 2021, 21:26:

**Pull request closed without merging**
