### PR TITLE
Release 4.7

### LINKED ISSUE #868: Error in dialects of Botlikh (botl1242)
The subclassification of Botlikh distinguishes Nuclear Botlikh and Zibirkhalin, which is incorrect. Zibirkhali is a Godoberi-speaking village. The page refers to a paper by Gudava (1964) as the source for the subclassification, but the paper in question does not mention Zibirkhali. It mentions Botlikh (proper) and Miarso. These are the two main dialects of the language (as all of the sources cited on the page will tell you), which correspond to villages with the same name. There is a third Botlikh village called Ashino, which also has its own subdialect with minor differences from Botlikh proper according to speakers, but it has never been studied.

As far as I know, this persistent error of Zibirkhali being a dialect of Botlikh, which is repeated in many online resources, originates from Ethnologue. I find it rather surprising that it would surface on Glottolog, which does not cite Ethnologue as a source.

### LINKED ISSUE #871: Gulf Coast French (gulf1242) likely extinct as of 2005 according to University of Mississippi panel
According to a linguistics panel at the University of Mississippi, Gulf Coast French likely went extinct in 2005 due to the impact of Hurricane Katrina. https://www.newswise.com/articles/linguistics-panel-examines-katrinas-impact-on-gulf-coast-languages

### LINKED ISSUE #872: Some varieties listed as both languages and dialects
[Faeto and Celle San Vito Francoprovencal](https://glottolog.org/resource/languoid/id/faet1240) is also listed as two dialects of Arpitan under the names [Celle San Vito](https://glottolog.org/resource/languoid/id/cell1238) and [Faeto](https://glottolog.org/resource/languoid/id/faet1239), [Walloon](https://glottolog.org/resource/languoid/id/wall1255) is also listed as a dialect of French under the name [Wallon](https://glottolog.org/resource/languoid/id/wall1259) which appears to be the French name for the Walloon language, and the [Hachijō](https://glottolog.org/resource/languoid/id/hach1239) language (written as Hachijo in its entry as a language, without the diacritic) is listed as a dialect of Japanese under the name [Hachijō](https://glottolog.org/resource/languoid/id/hach1238) (with the diacritic). Is this intentional? ~Sol

### LINKED ISSUE #885: Bathi and Bhatiyana - where do these Punjabi dialect names come from?
I am curious where the names of these entries come from:
* https://glottolog.org/resource/languoid/id/bath1239
* https://glottolog.org/resource/languoid/id/bhat1264

As far as I can tell Bathi and Bhatiyana are names of geographic regions rather than dialect names. However, even in *Linguistic Atlas of the Punjab* (H. S. Gill, 1973), one of the only comprehensive regional dialect surveys of Punjabi, this is not a distinction which is brought up. Maybe something has been written about this but there are no references listed to find where this comes from

### LINKED ISSUE #903: Reference 27788 linked to wrong language
Reference [27788](https://glottolog.org/resource/reference/id/27788) is erroneously linked to Banda (Indonesia) [bnd]. It should be linked to Mono (Democratic Republic of Congo) [mnh] only. Also, its macroarea should be Africa only.

### PR DESCRIPTION
**Pull request by xrotwang**
closes #903
closes #885
closes #872
closes #871
closes #868

### CODE REVIEW

**Review by xflr6 — APPROVED** [review]
LGTM.

- tried in https://github.com/glottolog/treedb/commit/b8a2ed59b3607da728a90dcab65b05e220c5ff40
- tests: https://github.com/glottolog/treedb/actions/runs/3596170344
- notebook: https://nbviewer.org/github/glottolog/treedb/blob/glottolog-4.7/Stats.ipynb

**Comment by xflr6** [comment]
Some noteworthy changes:
- 9 identifiers less
- ~20,000 links less
- ~400 more timespans
- 4 more endangerments
- 2 more isolates
- 1 mixed language less

**Comment by xrotwang** [comment]
I removed the links to Crubadan, because the site has been down for a
couple of months now.

Sebastian Bank ***@***.***> schrieb am Do., 1. Dez. 2022,
21:33:

**Comment by xrotwang** [comment]
> * 9 identifiers less

Explained by fewer WALS languages (some merging happened in recent WALS revisions) and a couple lost Wikidata links.

**Comment by xflr6** [comment]
Just checking: we will add the `v4.7` tag once the new version is deployed, right (https://github.com/glottolog/glottolog/blob/master/RELEASING.md#releasing)?

**Comment by xrotwang** [comment]
glottolog-cldf will include quite a bit of new stuff, so I'm still working on creating that - which may require tweaks to pyglottolog. Once that's done, I'd release pyglottolog, then add the tag here, then release glottolog-cldf.

Additionally, we also came across some inconsistencies relating to timespans. So there's probably another PR going to be opened (and merged) before v4.7 is really complete. Correct @d97hah ?

**Comment by d97hah** [comment]
Right see https://github.com/glottolog/glottolog/pull/908

Pada tanggal Jum, 2 Des 2022 pukul 17.39 Robert Forkel <
***@***.***> menulis:

**Pull request merged**
