### PR TITLE
Release 4.4

### PR DESCRIPTION
**Pull request by xrotwang**
Please review (but leave merging to me).

### CODE REVIEW

**Comment by xflr6** [comment]
Thanks Robert.

Roundtrip fixes in 5da49af63fe2f08984a427dba64242808a60fd08, can you merge/include that into the PR ([temp branch](https://github.com/glottolog/glottolog/compare/release-4-4-roundtrip))?

Just in case: this branch is behind (does not include) 3b997d1da3b7feeacddc9c9692223d4a1c30af81 from `master` (yet?).

**Comment by xflr6** [comment]
Quickly looked at [Stats.ipynb](https://nbviewer.jupyter.org/github/glottolog/treedb/blob/master/Stats.ipynb) when ran with this branch.

Compared to 4.3, we slightly reduce the number of values/entries for (maybe confirm this is expected?):
- identifier > multitree
- identifier > languagelandscape
- hh_ethnologue_comment
- bookkeeping languages

Counts (round number  of languoids :)
```
25,900 languoids
   245 families
   182 isolates
   427 roots
 8,533 languages
 4,326 subfamilies
12,796 dialects
 7,613 Spoken L1 Languages
   202 Sign Language
   122 Unclassifiable
    83 Pidgin
    68 Unattested
    31 Artificial Language
    11 Mixed Language
    14 Speech Register
 8,144 All
```
- +407 languoids
- +1 family
- +1 isolate
- +2 roots

**Comment by xrotwang** [comment]
Except for the decrease of Bookkeeping languages, these changes seem reasonable.

**Comment by xrotwang** [comment]
Just checked: The diff
```diff
$ diff book4_3.txt book4_4.txt 
431,432d430
< ├── meng1263
< │   └── md.ini
475,476d472
< ├── nkoa1234
< │   └── md.ini
685,686d680
< ├── teke1279
< │   └── md.ini
788c782
< 392 directories, 393 files
---
> 389 directories, 390 files
```
can be explained by all these 3 languages having been moved to other places in the classification. So all good.

**Comment by xflr6** [comment]
Thanks for confirming, should be good to go then.

**Comment by d97hah** [comment]
Approve

**Pull request merged**
