### PR TITLE
Update md.ini

### PR DESCRIPTION
**Pull request by HaikalFK**
"Kuningan Sundanese" is a part of the Cirebon Sundanese dialect family.

### CODE REVIEW

**Comment by d97hah** [comment]
What is your source for this claim?

Pada tanggal Sel, 22 Nov 2022 pukul 04.33 Haikal ***@***.***>
menulis:

**Comment by HaikalFK** [comment]
Abdurrachman; Umsari, O.S.; Zarkasih, R. (1985). [Struktur Bahasa Sunda Dialek Cirebon] (https://archive.org/details/struktur-bahasa-sunda-dialek-cirebon). Jakarta: Pusat Pembinaan dan Pengembangan Bahasa. [OCLC] (https://id.wikipedia.org/wiki/OCLC) [14148023] (https://www.worldcat.org/oclc/14148023).

You can see at page ix
at page ix you can see it in the first paragraph which reads:

Penelitian struktur bahasa Sunda dialek Cirebon ini merupakan realisasi tugas yang diberikan oleh Proyek Penelitian Bahasa dan Sastra Indonesia dan Daerah Jawa Barat. Yang dimaksud dengan bahasa Sunda dialek Cirebon ini ialah bahasa-bahasa yang dipergunakan di Kabupaten Kuningan, sebagian besar di Kabupaten Majalengka, sepertiga bagian di Kabupaten Cirebon, dan sebagian kecil di Kabupaten Indramayu

which meanings:

This research on the structure of the Sundanese dialect of the Cirebon dialect is the realization of a task given by the Indonesian Language and Literature Research Project and the West Java Region. What is meant by the Cirebon dialect of Sundanese are the languages ​​used in Kuningan Regency, mostly in Majalengka Regency, one-third part in Cirebon Regency, and a small part in Indramayu Regency.

Thus, it is emphasized that the Sundanese dialect spoken in the Kuningan, Majalengka, and Indramayu areas is a collection of sub-dialects which are part of a dialect known as Cirebonese Sundanese.

**Comment by HaikalFK** [comment]
Some references about Kuningan dialect or sub-dialect:
* https://ejournal.upi.edu/index.php/JPBSI/article/download/32534/pdf
* https://www.academia.edu/29742274/SUNDANESE_ISOGLOSSES_OF_LEXICAL_VARIATION_IN_KUNINGAN

**Comment by d97hah** [comment]
The change you have suggested in the md.ini is to rename Cirebon Sundanese
to Kuningan while your text suggests something else (Kuningan to be added
as a sub-dialect of Cirebon? of Mid-East  Sundanese?). all the best, H

Pada tanggal Jum, 25 Nov 2022 pukul 06.40 Haikal ***@***.***>
menulis:

**Comment by HaikalFK** [comment]
What I want to suggest is to rename Cirebon Sundanese to Kuningan Sundanese, and rename Mid-East Sundanese to Cirebon Sundanese, or just delete this Cirebon Sundanese and create a new md.ini for Kuningan Sundanese. Because "Cirebon Sundanese" refers to a set of dialects spoken in the Eastern region of Sundanese speaking. Which contains several dialects, such as Kuningan Sundanese (East-Coast Sundanese), Majalengka Sundanese (Mid-East Sundanese), and Indramayu Sundanese (Non-h dialect).

**Comment by d97hah** [comment]
The source you cite does not say there is a special dialect in Kuningan,
only that Cirebon Sundanese is spoken in this Kabupaten. I can't find clear
support for the Kapubaten-based division in the detailed study of Nothofer
(1980), but since the other Kabupatens are listed separately in Glottolog,
we might as well add Kuningan so I'll do that for next version. I'll keep
the name Mid-East Sundanese [cire1239] to avoid confusion with the specific
variety spoken in the Cirebon Kabupaten specifically. all the best, H

Pada tanggal Sab, 26 Nov 2022 pukul 01.37 Haikal ***@***.***>
menulis:

**Pull request closed without merging**
