### PR TITLE
Miscfixes

### PR DESCRIPTION
**Pull request by d97hah**
Sorry for big commit. This is my first Python 3 commit btw!

### CODE REVIEW

**Comment by xrotwang** [comment]
This is the first time I used GitHub's "Hooray" emoji.

**Comment by xrotwang** [comment]
@d97hah  Where did `hv:Novak:Eastern-Iranian:2013` and `hh:hv:Bakker:Three-Dutch-Creoles` - and possibly a couple more - go? These are still referenced in (sub-)classifaction comments.

**Comment by xrotwang** [comment]
This one `hh:hvld:Urban:Peruvian-North-Coast` is rather new, right? So maybe you didn't commit an updated hh.bib?

**Comment by d97hah** [comment]
Indeed, my old script had a path (pyhton27 that needed to be updated to
python38). Just pushed a new hh.bib. Glottolog check gives some
.ini-reference errors due to key changes. Were we going to get rid of the
.ini-references or did I dream that? If not, I'll fix the .ini:s.

Pada tanggal Jum, 10 Jan 2020 pukul 16.47 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Let me have a look.

d97hah <notifications@github.com> schrieb am Sa., 11. Jan. 2020, 18:43:

**Comment by xrotwang** [comment]
Everything that says `missing source` will be fixed automatically, the rest needs manual fixing. I'll take care of this.

**Comment by d97hah** [comment]
Ok pushed fixes for the rest

Pada tanggal Min, 12 Jan 2020 pukul 16.04 Robert Forkel <
notifications@github.com> menulis:

**Pull request merged**
