### PR TITLE
fix missing newline separator in source references

### PR DESCRIPTION
**Pull request by xflr6**
- cf. e.g. https://glottolog.org/resource/languoid/id/eski1264

### CODE REVIEW

**Comment by d97hah** [comment]
These were generated by:

l.cfg.set('classification', 'familyrefs', rerefsplit.split(familyrefs))
l.write_info(outdir=l.dir)

the issue should ideally be fixed there.

all the best,
H



Pada tanggal Jum, 20 Mar 2020 pukul 09.01 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@d97hah cannot reproduce the issue. Here's what `cfg.set` does: https://github.com/clld/clldutils/blob/92ab4cab4f9a39e0d6f20f09ef75e0ea4a11d025/src/clldutils/inifile.py#L25-L34
Local testing with passing in a `list` of refs works as expected - i.e. each ref on a new line. What type does `rerefsplit.split(familyrefs)` return - maybe a generator?

**Comment by xrotwang** [comment]
@d97hah or your pattern fails to split the string as expected, so the whole thing is returned as 1-element list?

**Comment by d97hah** [comment]
Hi RObert! Yes, that's the problem, it failed to split when the previous
ref has page numbers. I'll fix and PR.

Pada tanggal Kam, 26 Mar 2020 pukul 17.14 Robert Forkel <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
Hi Robert! (Not directly related to newlines in sources), but suppose I
update AES sources with

gl.aes_sources[fvcnsp] = AESSource(id=fvcnsp, name=fv, url=None,
reference_id=k, pages=o.group("pages") or None)

how do I flush this to disk? (Corresponding to l.write_info(outdir=l.dir)
for languoid objects)


Pada tanggal Jum, 27 Mar 2020 pukul 10.07 Harald Hammarström <
harald.hammarstrom@gmail.com> menulis:

**Comment by xrotwang** [comment]
@d97hah Config data like `aes_sources` is read-only. I.e. to add to it, you'd have to edit [`config/aes_sources.ini`](https://github.com/glottolog/glottolog/blob/master/config/aes_sources.ini) "by hand".

**Pull request merged**
