### PR TITLE
Nov2019

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xflr6** [comment]
Hi @d97hah just checking: is `Nyima and Suzuki (2019:58)` the intended value for (a new) endangerment source (https://github.com/glottolog/glottolog/commit/4c60bc704e3aedaf5a6c51c6437a3853f0e4a743#diff-08d13df6b8604ce708680e0535926d30R34)? The values so far seem to use abbreviations.

**Comment by d97hah** [comment]
Yes, is that a problem? I foresee there might be a few dozen more of these
in the future, on lgs which are not in the databases with abbreviations

Pada tanggal Sen, 18 Nov 2019 pukul 18.04 Sebastian Bank <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@xflr6 good catch! @d97hah endangerment sources are listed here https://github.com/glottolog/glottolog/blob/master/config/aes_sources.ini
So adding more isn't a problem, but it should happen in sync with this file

**Comment by xrotwang** [comment]
Will add a check for this now.

**Comment by xrotwang** [comment]
So with the check I get
```
ERROR   Lamo [lamo1245]: endangerment: KeyError: 'Nyima and Suzuki (2019:58)'
```
:)

Dunno whether adding "a few dozen more" to `aes_sources.ini` makes sense, though. Alternatively, we could allow reference IDs here, e.g. `benjamins:ltba.18004.nyi.xml` for the Nyima and Suzuki paper - or the equivalent in `hh.bib`.

**Comment by xrotwang** [comment]
@xflr6 I adopted the "reference ID as AES source" solution, see https://github.com/glottolog/glottolog/commit/c303f635847877c8b04bd3b21874e113859f8af4
`pyglottolog` will then create an `AESSource` instance on-the-fly.

**Comment by d97hah** [comment]
Very good solution! H

Pada tanggal Sel, 19 Nov 2019 pukul 10.22 Robert Forkel <
notifications@github.com> menulis:

**Pull request merged**
