### PR TITLE
Nauruan

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by d97hah** [comment]
NB1: I realise this reintroduced double spaces between some refs, is this important? If so I'll try to figure out the cause. AFAIK I am only using the cfg-write interfaces
NB2: Tell me when to stop pushing new things

**Comment by xflr6** [comment]
> I realise this reintroduced double spaces between some refs, is this important?

Never mind, we can re-apply.

**Comment by xrotwang** [comment]
@xflr6 do you want to reapply before merge or in a separate PR?

**Comment by xflr6** [comment]
I think it's simpler to re-do afterwards.

**Comment by xrotwang** [comment]
@d97hah What about dec 1st as deadline for anything that should go into Glottolog 4.5?

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
