### PR TITLE
Updates iso-hh-comments

### PR DESCRIPTION
**Pull request by d97hah**
These needed some serious updating. A question is whether the comments should be there at all if the most current ethnologue version (now E23) no longer features the missing/spurious language?!

### CODE REVIEW

**Comment by xrotwang** [comment]
I'd say these comments should ideally only address the latest version of Ethnologue - so Glottolog 4.0 will have comment about E22, Glottolog 4.2 about E23, etc. These comments will always be preserved in the git history which is sufficient considering that they are only/mostly historically relevant.

**Comment by d97hah** [comment]
Ok let me fix with a new PR

Pada tanggal Sel, 7 Apr 2020 pukul 20.51 Robert Forkel <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
Ok how about now?

Pada tanggal Sel, 7 Apr 2020 pukul 20.52 Harald Hammarström <
harald.hammarstrom@gmail.com> menulis:

**Comment by d97hah** [comment]
Ok should be fixed now!

Pada tanggal Rab, 8 Apr 2020 pukul 12.18 Robert Forkel <
notifications@github.com> menulis:

**Pull request merged**
