### PR TITLE
Release 4.5

### PR DESCRIPTION
**Pull request by xrotwang**

### CODE REVIEW

**Comment by d97hah** [comment]
Looks fine to me

**Comment by xflr6** [comment]
@xrotwang: just to make sure, does https://github.com/glottolog/glottolog/tree/mandadanchetti maybe have an unmerged commit (14b71ddaefd93eebaf4cee274b55d3d78f8c342d, hard to tell from all the merge commits)?

**Comment by xrotwang** [comment]
> @xrotwang: just to make sure, does https://github.com/glottolog/glottolog/tree/mandadanchetti maybe have an unmerged commit ([14b71dd](https://github.com/glottolog/glottolog/commit/14b71ddaefd93eebaf4cee274b55d3d78f8c342d), hard to tell from all the merge commits)?

Yes, looks like it. But the changes in this commit will be in master anyway, because I re-run the script synching bibfiles and md.inis before releases.

**Comment by xflr6** [comment]
Thanks for confirming, delete the obsolete branch then?

**Comment by xrotwang** [comment]
done

**Comment by xflr6** [comment]
Some observations we might double check:

- 1 new bibfile
- 3 new endangerment sources
- 1 more classification familyrefs
- ~60 new endangerments
- 1 less hh_ethnologue_comment (intended?)
- 13 less identifiers > multitree
-  ~20 less triggers > lgcode

stats before (`v4.4`):
```
25,900 languoids
245 families
182 isolates
427 roots
8,533 languages
4,326 subfamilies
12,796 dialects
7,613 Spoken L1 Languages
202 Sign Language
122 Unclassifiable
83 Pidgin
68 Unattested
31 Artificial Language
11 Mixed Language
14 Speech Register
8,144 All
```

after (3 more spoken L1 languages, 8 more sign languages, 1 less unclassifyable, 1 more register):

```
26,101 languoids
245 families
182 isolates
427 roots
8,549 languages
4,348 subfamilies
12,959 dialects
7,616 Spoken L1 Languages
210 Sign Language
121 Unclassifiable
83 Pidgin
68 Unattested
31 Artificial Language
11 Mixed Language
15 Speech Register
8,155 All
```

**Comment by xrotwang** [comment]
Sounds all plausible to me. @d97hah do you remember which Ethnologue comment may have been purged?

**Comment by xrotwang** [comment]
Maybe we can turn this into some kind of automated CHANGELOG? What seems relevant for users:
- new bibfiles
- new endangerment sources
- diffs in languoid per category numbers

**Comment by xrotwang** [comment]
But then - most of this is only one git command away?
```shell
$ git diff v4.4...v4.5 config/aes_sources.ini
diff --git a/config/aes_sources.ini b/config/aes_sources.ini
index 1308b272b6..1cb60293d2 100644
--- a/config/aes_sources.ini
+++ b/config/aes_sources.ini
@@ -180,3 +180,15 @@ reference_id =
 [NicholasEvans]
 name = Nicholas Evans (p.c. 2021)
 reference_id =
+
+[Tschonghongei]
+name = Tschonghongei 2018
+reference_id = hh:g:Tschonghongei:Mbuk
+
+[Golla]
+name = Golla 2011
+reference_id = hh:hvb:Golla:California
+
+[HeineKonigandLegere]
+name = Heine et al 2015
+reference_id = hh:s:Heine:Akie
```

**Comment by xflr6** [comment]
Rendering an overview of changes sounds nice to have to me.

+1 that for the `config/` files git might suffice, but maybe not for languoid stats.

**Comment by d97hah** [comment]
No, but whatever it was, it was most likely intentional.

Pada tanggal Jum, 10 Des 2021 pukul 12.10 Robert Forkel <
***@***.***> menulis:

**Comment by xflr6** [comment]
Released [`treedb` 2.4.1](https://pypi.org/project/treedb/2.4.1/#files).

**Pull request merged**
