### PR TITLE
fix file line ending for jude1263/md.ini

### PR DESCRIPTION
**Pull request by xflr6**
- follow-up 9aa3afbb1382372f174065de1dbaa1a38b42c97d

### CODE REVIEW

**Comment by xflr6** [comment]
We can still add commits until we tag the release right?

**Comment by xrotwang** [comment]
ok

**Comment by xrotwang** [comment]
Does a deadline of tonight work for you, though? :)

**Comment by xflr6** [comment]
Notebook diff: https://github.com/glottolog/treedb/compare/latest

Notebook: https://nbviewer.org/github/glottolog/treedb/blob/latest/Stats.ipynb

For  `abin1243` (some examples), are we removing some things intentionally (elcat)?

(Re?)-introducing `15 Speech Register`? Otherwise nothing off?

**Comment by xrotwang** [comment]
Removal of some elcat mappings is intentional.

**Comment by xrotwang** [comment]
@d97hah what do you think about the speech register issue?

**Comment by xrotwang** [comment]
(I admit I already released to Zenodo - so the question becomes if any of this is worth a path release :) )

**Comment by d97hah** [comment]
Forgive my ignorance, but what Speech Register issue?

**Comment by xrotwang** [comment]
Looking at
https://github.com/glottolog/treedb/compare/latest#diff-c0729e2fdcca8856ab63bef7bd5412a1f7d71ce2c9e5766403f6edc681f16ddfR2944
and
https://github.com/glottolog/treedb/compare/latest#diff-c0729e2fdcca8856ab63bef7bd5412a1f7d71ce2c9e5766403f6edc681f16ddfL2997
I'd think there is no issue. Agree, @xflr6 ?

**Comment by d97hah** [comment]
No issue AFAICT

Pada tanggal Rab, 25 Mei 2022 pukul 07.01 Robert Forkel <
***@***.***> menulis:

**Comment by xflr6** [comment]
Thanks for checking; I see now that the output for the languoid stats are just divided intwo output cells.

**Pull request merged**
