### PR TITLE
fix countries alphabetic order

### PR DESCRIPTION
**Pull request by xflr6**
- follow-up: 0bde428bfa2735e95a31109e1825cce6c0ab7cae, 49994e21a6b0affada8525574de5d4641f4d9097, 9c1accbff0fd666596a7af7f6c36951d1348f442

### CODE REVIEW

**Comment by xflr6** [comment]
Hi guys, I  was wondering if it would be worth to change the order of country name and CC  from e.g. `Åland Islands (AX)` to something like `AX (Åland Islands)`  do they sort by code by deault, maybe not (we could also remove the names, which micht be simpler to maintain in the long  run)?

**Comment by xrotwang** [comment]
Regarding order, I don't have a strong opinion. Regarding dropping language
names: yes, that might simplify things. The names are not used, anyway,
only the code is used to lookup the metadata from pycountry. So I guess in
the worst case - when code and name are out of sync - they do not even
serve as mnemonic device.

d97hah <notifications@github.com> schrieb am Sa., 28. Nov. 2020, 13:12:

**Comment by xflr6** [comment]
Thanks. @d97hah: if you agree I can start preping PRs for `pyglottolog`, `treedb` and the `md.ini` files here.

**Comment by d97hah** [comment]
I don't disagree

Pada tanggal Sab, 28 Nov 2020 pukul 13.23 Sebastian Bank <
notifications@github.com> menulis:

**Comment by xflr6** [comment]
Allright, opened #635 for this and self-assigned.

**Pull request merged**
