### PR TITLE
E25endangerment

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xrotwang** [comment]
Hm. 4006 changed files is quite a bit. Can we be sure that only endangerment info has been changed - and **classification**?
I always used GitHub's diff viewer to check for indications of classification changes gone wrong.

**Review by xrotwang — CHANGES_REQUESTED** [review]
For `hh.bib` I get the following errors:
```
repeated bibliograhpy entry: phon:Sakine:Zerenkel
repeated bibliograhpy entry: typ:Mariati:Tarfia
repeated bibliograhpy entry: ld:Ivani:Suansu
DuplicateField('entry with key ld:Harley:Mandara-Bata has a duplicate volume field')
entry with key ld:Harley:Mandara-Bata has a duplicate volume field
DuplicateField('entry with key vld:Roberts:Boor has a duplicate volume field')
entry with key vld:Roberts:Boor has a duplicate volume field
```
Can you fix?

**Comment by d97hah** [comment]
It's the same script of mine that does this every year and that
script can't change the clf. Now in this PR I had some github issues and
about a dozen other cued changes crept in (incl some on clf), so "sure" is
a strong word but afaik there should be appx 4000 endangerment changes and
a dozen others.

Pada tanggal Sel, 3 Mei 2022 pukul 08.52 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
@d97hah are you going to fix hh.bib or should I?

**Review by xrotwang — APPROVED** [review]

**Comment by xrotwang** [comment]
ok. I compared the language/dialect/family counts to previous master. looks like nothing substantial changed.

**Comment by d97hah** [comment]
Fixed and pushed now (NB I get an error from glottolog-admin check I don't
understand and haven't had time to dig into (see below, in case something
pops up to you)

WARNING Baga Mboteni [baga1276]: <ISO-639-3 [bgm] Retirement/duplicate>
changed to [bcg]
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\glottolog-admin.exe\__main__.py", line 7, in
<module>
  File "c:\python38\lib\site-packages\pyglottolog\__main__.py", line 24, in
admin_main
    return _main(pyglottolog.admin_commands, **kw)
  File "c:\python38\lib\site-packages\pyglottolog\__main__.py", line 71, in
_main
    return args.main(args) or 0
  File "c:\python38\lib\site-packages\pyglottolog\admin_commands\check.py",
line 105, in run
    assert isinstance(lang.macroareas, list)
  File "c:\python38\lib\site-packages\pyglottolog\languoids\languoid.py",
line 455, in macroareas
    return [
  File "c:\python38\lib\site-packages\pyglottolog\languoids\languoid.py",
line 456, in <listcomp>
    self._api.macroareas.get(n)
  File "c:\python38\lib\site-packages\pyglottolog\config\__init__.py", line
194, in get
    raise ValueError(item)
ValueError: UNKNOWN

Pada tanggal Sel, 3 Mei 2022 pukul 15.49 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
@d97hah at some point, you had `UNKNOWN` as value for macroareas in a couple languoid files. Maybe some of these still lay around in your checkout? `glottolog-admin check` runs fine for me on master
```shell
$ git describe
v4.6-19-g6a4dfc2513
```
Maybe `grep -r UNKNOWN languoids` helps with debugging here.

**Pull request merged**
