### PR TITLE
Update md.ini

### PR DESCRIPTION
**Pull request by Laitei40**
Corrected some mistakes.

### CODE REVIEW

**Comment by xrotwang** [comment]
It seems you suggest to rename Mara Chin to Mara. What are the reasons for this suggestion? Also, note that the alternative names section has the explicit purpose of listing - well - alternative names of a language as used elsewhere. So changing the WALS of a language here does not make much sense, when the name doesn't change at [WALS](https://wals.info/languoid/lect/wals_code_cmr).

**Comment by Laitei40** [comment]
The name "Mara Chin" combines Mara (the people) and Chin (a state in Myanmar). However, not all Mara people live in Myanmar’s Chin State; many reside in Mizoram, India, where the Mara population is larger and does not identify with the term "Mara Chin." In India, Mara people exclusively refer to themselves as "Mara" in both speech and writing. The term "Mara Chin" is unfamiliar to many Mara, suggesting it originated with someone from Myanmar, and it is not accepted as representative by the Mara community.

References: https://mara-people.web.app/

**Comment by xrotwang** [comment]
@d97hah So the question here is only, whether we change the Glottolog name of Mara Chin. The other changes in the *.ini file shouldn't be applied.

**Comment by Laitei40** [comment]
Thank you for clarifying. Yes, we are requesting only a change to the Glottolog name, replacing "Mara Chin" with "Mara," as it better aligns with the community's preferred identity. Other adjustments in the *.ini file are not necessary.

We appreciate your support in helping represent the Mara community accurately.

**Comment by d97hah** [comment]
The name change is well-founded. See this PR which includes the name change
(plus keeping the old as an alias).
https://github.com/glottolog/glottolog/pull/1110

Sorry I would have acted on this PR earlier except I wanted to wait for 5.1
to appear, but I see it's already up! H

Pada Sel, 5 Nov 2024 pukul 10.44 Laitei40 ***@***.***>
menulis:

**Comment by xrotwang** [comment]
The relevant change is in #1110 - will appear on https://glottolog.org after the next release, i.e. some time in spring 2025.

**Comment by Laitei40** [comment]
Thank you so much for approving the name change to "Mara" and including "Mara Chin" as an alias in PR #1110. Your support in accurately representing our community’s identity means a lot to us. We appreciate your efforts and patience in finalizing this change, especially with the timing around the 5.1 release.

Warm regards,
Laitei and the Mara Community

**Pull request closed without merging**
