### PR TITLE
Recognition of IE/CIE, recognition of Golo + Dongo + Disa, updates in…

### PR DESCRIPTION
**Pull request by d97hah**
… Salish + Athabaskan + Adamawa + Gur + Algonquian + Berber + Sogeram + subclf, newer sources for Cushitic + Saharan + C Sudanic, positioning of Mbugu and Mednyj Aleut, addition of interslavic, Kamrupa fix, coordinated + hh.bib + misc dialect fixes.

### CODE REVIEW

**Review by xrotwang — COMMENTED** [review]
Hm. That's pretty big. Would have preferred one PR per family.
I think, I'll need more checks - e.g. for dropped language-level nodes - to review this one.

**Comment by d97hah** [comment]
You have to approve and merge the previous ones quicker so they don't pile
up :-) Shouldn't be any dropped ll nodes in this one

Pada tanggal Sen, 7 Sep 2020 pukul 21.34 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Looks good so far. More checks is a good thing anyway (I might take a two-week vacation one day :) ) - even if the changes are below GitHub's display limit of **3,000** changed files.

**Comment by xrotwang** [comment]
Ok, so the stats look less intimidating than the "raw" diff:
```
INFO    All 8513 language level languoids still present
INFO    5 family level languoids deleted
INFO    3 dialect level languoids deleted
```

**Pull request merged**
