### PR TITLE
Create bahn1262

### PR DESCRIPTION
**Pull request by ChinQuoc**
Update bahn1262

### CODE REVIEW

**Comment by xrotwang** [comment]
This language already exists elsewhere in the classification. Do you mean to propose an alternative classification? And if so, what's the source for this proposal?

**Comment by ChinQuoc** [comment]
That's right, you're the one to move it elsewhere, because I don't know how to move it, so I had to

**Comment by ChinQuoc** [comment]
please, move it to i just suggested, if you need the document i will send it via gmail, for your reference

**Comment by xrotwang** [comment]
Do you have a source justifying the classification of Bahnar under [Rengao](https://glottolog.org/resource/languoid/id/reng1252) rather than [Tampuon-Bahnar](https://glottolog.org/resource/languoid/id/tamp1256)?

**Comment by xrotwang** [comment]
> please, move it to i just suggested, if you need the document i will send it via gmail, for your reference

Please send to glottolog@eva.mpg.de

**Comment by ChinQuoc** [comment]
> Do you have a source justifying the classification of Bahnar under [Rengao](https://glottolog.org/resource/languoid/id/reng1252) rather than [Tampuon-Bahnar](https://glottolog.org/resource/languoid/id/tamp1256)?

I'm a native there

**Comment by xrotwang** [comment]
I see. We typically require an academic publication to justify classification of a language, though, to make sure it can be reviewed and vetted.

**Comment by ChinQuoc** [comment]
> > please, move it to i just suggested, if you need the document i will send it via gmail, for your reference
> 
> Please send to [glottolog@eva.mpg.de](mailto:glottolog@eva.mpg.de)

Ok

**Comment by xrotwang** [comment]
Genealogical classification is something linguists argue a lot about. And it's not just closeness. Languages can be very close due to contact, too. So there would need to be some reviewable evidence for any claim about classification.

**Comment by ChinQuoc** [comment]
> Genealogical classification is something linguists argue a lot about. And it's not just closeness. Languages can be very close due to contact, too. So there would need to be some reviewable evidence for any claim about classification.

Yes, Bahnar Rengao all respond to that

**Comment by xrotwang** [comment]
Bahnar seems to be a name used for multiple languages (see https://glottolog.org/glottolog?name=Bahnar&namequerytype=part), so maybe you are refering to a different one? Also note that the reference Glottolog gives for its classification is [Sidwell 2021](https://glottolog.org/glottolog?name=Bahnar&namequerytype=part), while the wikipedia pages you reference quote an older source, Sidwell 2015.

**Comment by ChinQuoc** [comment]
> Bahnar seems to be a name used for multiple languages (see https://glottolog.org/glottolog?name=Bahnar&namequerytype=part), so maybe you are refering to a different one? Also note that the reference Glottolog gives for its classification is [Sidwell 2021](https://glottolog.org/glottolog?name=Bahnar&namequerytype=part), while the wikipedia pages you reference quote an older source, Sidwell 2015.

Bahnar exists many languages ​​that are its children, including Jolong, Rengao, Glar, Tolo, Bonom, Kriem, Roh, KonKde but the surnames do not exist in Glottolog except for its Rengao which already exists.

**Comment by ChinQuoc** [comment]
Tampuon is not related to Bahnar, and its related Bahnar cousins ​​Sedang, Todrad, Jeh, Halang and its offspring Rengao

**Comment by ChinQuoc** [comment]
it lies north of Bahnaric or Northeast of Bahnaric, it is not west of
Bahnaric

Vào 23:03, T.4, 1 Th6, 2022 Robert Forkel ***@***.***> đã
viết:

**Pull request closed without merging**
