### PR TITLE
Added different spellings that are used

### PR DESCRIPTION
**Pull request by psubhashish**
Ref. Wikipedia article (Baleswari Odia). Also, I am a native speaker and have contributed in documenting it (see https://commons.wikimedia.org/wiki/File:Oral_history_of_Odisha_-_Storytelling.webm)

### CODE REVIEW

**Comment by xrotwang** [comment]
Thanks for this contribution! You've added the alternative spellings under the `multitree`heading, though, so I moved them to a more appropriate place.

**Comment by psubhashish** [comment]
Thanks @xrotwang for that. For some reason, I can't find it yet on [Glottolog](https://glottolog.org/resource/languoid/id/nort2660) or is there a different place I should be looking at?

Also, how could we contribute and add references as that seems to be totally empty at the moment?

**Comment by xrotwang** [comment]
As stated here https://glottolog.org/meta/downloads , the website serves the latest released version of the data in this repository. We released v4.4 earlier this month, so your changes may only show up with v4.5, later this year.

**Comment by xrotwang** [comment]
Regarding references: You could send us a BibTeX file with references, containing a field `lgcode` such as
```bibtex
@misc{AuthorYear,
    title = {...},
    lgcode = {nort2660},
    ....
}
```
and we can add that as reference provider to https://github.com/glottolog/glottolog/blob/master/references/BIBFILES.ini

**Pull request merged**
