### PR TITLE
Many updates relating to the release of Ethnologue 26 + misc clf changes

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xrotwang** [comment]
@d97hah what about these:
```
ERROR   Southwestern Tasmanian [sout3391]: timespan specified for non-extinct languoid
ERROR   Northwestern Tasmanian [nort3415]: timespan specified for non-extinct languoid
ERROR   Dokshi [lush1256]: timespan specified for non-extinct languoid
ERROR   Tulai [nucl1693]: timespan specified for non-extinct languoid
ERROR   Loup B [loup1245]: timespan specified for non-extinct languoid
```

Should I just update the corresponding status?

**Comment by d97hah** [comment]
I don't get those error msgs thru "glottolog-admin check", does that mean I
am running an old version or the like?

Anyway, see the last (giant, sorry) commit. Those five should be taken care
of by that one.



Pada tanggal Sel, 7 Mar 2023 pukul 13.33 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
> does that mean I am running an old version or the like?

Quite likely. This check is fairly recent: https://github.com/glottolog/pyglottolog/commit/5422436990d4068e8780cdbe12cea0a3db646e8d#diff-c5e885326f65937941744cf7c3d359a368627fb967b153f89262e73d550c00ea

**Comment by xrotwang** [comment]
It seems the latest commit added 8 more:
```
ERROR   Warázu [paus1244]: timespan specified for non-extinct languoid
ERROR   Western Yiddish [west2361]: timespan specified for non-extinct languoid
ERROR   Mangala [mang1383]: timespan specified for non-extinct languoid
ERROR   Antakarinya [anta1253]: timespan specified for non-extinct languoid
ERROR   Amurdak [amar1271]: timespan specified for non-extinct languoid
ERROR   Iyongiyong [bakp1238]: timespan specified for non-extinct languoid
ERROR   Sambe [samb1307]: timespan specified for non-extinct languoid
ERROR   Gelao Mulao [gela1264]: timespan specified for non-extinct languoid
```

**Comment by d97hah** [comment]
Thanks, I've fixed in the last push

Pada tanggal Sel, 7 Mar 2023 pukul 15.44 Robert Forkel <
***@***.***> menulis:

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
