### PR TITLE
added/removed country codes FO, GL, DK, added coordinates for West Greenlandic Pidgin

### PR DESCRIPTION
**Pull request by hanzlan**

### CODE REVIEW

**Comment by xrotwang** [comment]
@hanzlan please keep individual PRs small and focused. Otherwise, merging is more difficult - e.g. in case only parts of the changes are accepted. Feel free to open multiple PRs, though.

**Comment by hanzlan** [comment]
Sorry, I will keep it in single PRs in the future

**Comment by hanzlan** [comment]
For future PRs I would like to ask if there's any basic rule behind country codes. Is it rather based on where the language evolved, where it is used as official language or where it is spoken today by a significant minority (maybe min. 5%) of L1 speakers today? Dutch is a good example for some really difficult cases in this respect: it evolved in the Netherlands and Belgium, but it is used as official language in Aruba, Bonaire, Curacao, Saba, Sint Eustatius, Sint Maarten and Suriname as well. The people of Aruba Bonaire and Curacao prefer to use Papiamentu in daily life, whereas Saba, Sint Eustatius and Sint Maarten's traditional language is Virgin Islands Creole, in Suriname's streets one mostly hears Sranan Tongo and Dutch. The same applies to English and French in various parts of this region.

**Comment by d97hah** [comment]
I think a better coordinate for W Greenlandic is Disko Bay (see van der Voort 1996) and there's a reason to put the Danish coordinate to the east if one considers (classic) Jutlandish as a separate lg. I'll merge this PR and adjust the coordinates back in retro. As you've noticed there's not really any serious curation of the country assignments that has a consistent policy re secondary migrations...

**Pull request merged**
