### PR TITLE
Release 5.0

### PR DESCRIPTION
**Pull request by xrotwang**
I'd aim at releasing on Monday, hope that works for you.

### CODE REVIEW

**Comment by d97hah** [comment]
The parts I have the chance to check (i.e not 3000 md.ini files) look fine.

**Comment by xflr6** [comment]
Thanks Robert, minor normalization in #1067

**Comment by xflr6** [comment]
Here is https://nbviewer.org/github/glottolog/treedb/blob/pre-glottolog-5/Stats.ipynb after #1067 mentioned above.

Diff is here: https://github.com/glottolog/treedb/compare/master...pre-glottolog-5?diff=unified (does not render on GH).

Here is it as a patch: [0001-re-run-Stats.ipynb-with-glottolog-219e79769109823e1e.patch](https://github.com/glottolog/glottolog/files/14551337/0001-re-run-Stats.ipynb-with-glottolog-219e79769109823e1e.patch)

Some random findings:

- `cldf.bib` reformatted completely
- number of `bibfiles` decreased from 42 to 37
- number of `identifier`s decreased by 11
- number of ISO retirements change to decreasyed by 11
- ~5k more `link`s
- number of `trigger`s decreased
- 1 new ISO code
- slightly fewer `multitree` and `elcat` `altnames`
- 100 more `glottolog` `altnames`
- slightly fewer `multitree` and `endangeredlanguages` `identifier`s
- 6 more `endangerment`s
- 1 more family and 1 more root
- 1 less `Unclassifiable` 
- new `endangerment` icon colors

HTH :)

**Comment by xrotwang** [comment]
@xflr6 the "random findings" sound all reasonable or expected to me. Thanks!

**Comment by xflr6** [comment]
Released `treedb`: https://pypi.org/project/treedb/2.6.3/

Notebook: https://nbviewer.org/github/glottolog/treedb/blob/master/Stats.ipynb

**Pull request merged**
