### PR TITLE
Update md.ini

### PR DESCRIPTION
**Pull request by ChinQuoc**
Change the name appropriately

### CODE REVIEW

**Comment by xrotwang** [comment]
What's the reasoning for prefering this name over the old one?

**Comment by ChinQuoc** [comment]
Because it doesn't match the local people's language

**Comment by xrotwang** [comment]
But that's the name of a Glottolog subgroup (https://glottolog.org/resource/languoid/id/hres1236), comprising multiple languages from different locations. Do you argue that there's still a shared local name for that subgroup?

**Comment by ChinQuoc** [comment]
Yes, those languages ​​are all children of Bahnaric

**Comment by xrotwang** [comment]
Indeed, and that's reflected in the Glottolog classification. The genealogical subgroup you want to rename, though, is a subgroup of Bahnaric, comprising the subgroups from which its name is formed. That's a convention we often use in Glottolog, because such subgroups are rather defined by extension than by a common name.

**Pull request closed without merging**
