### PR TITLE
Create md.ini

### PR DESCRIPTION
**Pull request by HaikalFK**
add a new dialect

### CODE REVIEW

**Comment by d97hah** [comment]
I've added Brebes "properly" i.e. with a generated glottocode and a
registry in glottocodes.json so this PR can be removed in favour of
https://github.com/glottolog/glottolog/pull/750

Pada tanggal Sen, 13 Sep 2021 pukul 10.42 Robert Forkel <
***@***.***> menulis:

**Comment by HaikalFK** [comment]
Thank for your help, but i want ask something, why the Brebes and Ciamis
dialect can't be seen in https://glottolog.org/resource/languoid/id/ ?
Sorry if my question is stupid.

Pada tanggal Sel, 14 Sep 2021 pukul 02.01 d97hah ***@***.***>
menulis:

**Comment by xrotwang** [comment]
https://glottolog.org serves released versions of the data in this repository. So Brebes and Ciamis will show up there after the next release, which we aim to do about three times a year.

**Comment by HaikalFK** [comment]
Okay, once again thank you so much for your great explanation

Pada tanggal Rab, 15 Sep 2021 pukul 13.31 Robert Forkel <
***@***.***> menulis:

**Pull request closed without merging**
