### PR TITLE
Update md.ini

### PR DESCRIPTION
**Pull request by ChinQuoc**
Cập nhật ngôn ngữ

### CODE REVIEW

**Comment by ChinQuoc** [comment]
Cập nhật cho ngôn ngữ

**Review by ChinQuoc — COMMENTED** [review]
Đây là đúng

**Comment by xrotwang** [comment]
Hi @ChinQuoc , you replaced an alternative name for a languoid in the ["multitree" category](https://github.com/glottolog/glottolog/pull/741/files#diff-9beb8593a661a088a4e1f93ac5cb172b8433c554a20fe85bc95007f526f99b10L43). These names have been taken over from [LinguistList's Multitree project](http://www.multitree.org/). So while they may be incorrect, it doesn't make much sense to change them, because they are basically provided as navigational device, to discover languoids by names they have been refered to in legacy projects.

**Comment by ChinQuoc** [comment]
Why is Bahnar language in West Bahnaric group, who moved it??  Bahnar
language is in the Northern Bahnaric group, and I see it's recently moved.
it must be in North Bahnaric group and especially it has to be with Rengao
and I don't know how to move it, looking forward to admin.
Link: https://glottolog.org/resource/languoid/id/bahn1262

Vào 17:02, T.2, 6 Th9, 2021 Robert Forkel ***@***.***> đã
viết:

**Comment by d97hah** [comment]
See pp 185-186

Sidwell, Paul. (2021) Classification of MSEA Austroasiatic languages. In
Paul Sidwell & Mathias Jenny (eds.), The Languages and Linguistics of
Mainland Southeast Asia: A Comprehensive Guide (World of Linguistics 8),
179-205. Berlin: Mouton.

Pada tanggal Min, 9 Jan 2022 pukul 13.28 ChinQuoc ***@***.***>
menulis:

**Comment by ChinQuoc** [comment]
I know, but it's not right to put it in the Tampon group, it used to be in
North Bahnaric, I'm from that ethnic group so I know
Link: https://glottolog.org/resource/languoid/id/bahn1264

Vào 21:02, CN, 9 Th1, 2022 d97hah ***@***.***> đã viết:

**Comment by ChinQuoc** [comment]
More information

Vào 21:02, CN, 9 Th1, 2022 d97hah ***@***.***> đã viết:

**Pull request closed without merging**
