### PR TITLE
May2021

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Review by xrotwang — CHANGES_REQUESTED** [review]
There's a language disappearing:
https://github.com/glottolog/glottolog/pull/722/files#diff-e9f81d3dd9bd244c18773e85e1218f77e75e720c8ab977d5f46abed3006883be

**Comment by d97hah** [comment]
Which one?

Pada tanggal Jum, 28 Mei 2021 pukul 17.48 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
koen1239

**Comment by d97hah** [comment]
hmm. what about now?

Pada tanggal Sab, 29 Mei 2021 pukul 19.18 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
Still, see https://github.com/glottolog/glottolog/pull/722/files#diff-e9f81d3dd9bd244c18773e85e1218f77e75e720c8ab977d5f46abed3006883be

**Comment by d97hah** [comment]
And now?

Pada tanggal Min, 30 Mei 2021 pukul 06.54 Robert Forkel <
***@***.***> menulis:

**Review by xrotwang — APPROVED** [review]

**Comment by xrotwang** [comment]
all good

**Pull request merged**
