### PR TITLE
fix of print.google.com references + makah-nitinaht subgrouping + mis…

### LINKED ISSUE #514: Khinalugh -> Khinalug
Dear all, is it possible to change language name in Glottolog, since _Khinalug_ is one used by specialists, and you have no reference with _Khinalugh_ variant (except some databases like [Ethnologue](https://www.ethnologue.com/language/kjj?__cf_chl_jschl_tk__=2a87cd2af5ee98e7d90cb0fea8d1b5990e7db692-1589013125-0-ASnHaZg6X1GLIcZMMil3_e5vImzWT6um_XnjKP1pR5mRwqkX4f1pPdfJjayzkXbX38drOwoY8qmDijOrEK-f-oaz-s0dqTRbEIXHmd4J_-jgSy0addgsidBFTFSLabETteFdiqgZhshTTGyar4XU4knQ7yt-eSgrlrV3yCvKvx3IKMbPX82G5l0grtS9m07vfsHu0w36C4tNvIida_OlEKtqLkmRtICtbFVHyI3jnqzvcxe49-xdA4a2z7ZMqLrrYW-XOz0v_sQ0x9dsBUFKFVCaHfADhBHTM2T_KKNs6BYA) and [SIL](https://iso639-3.sil.org/code/kjj))

### LINKED ISSUE #515: "print.google.com" URLs do not work
E.g. `http://print.google.com/print?id=U8IxYGujF-8C` - given as `url` for `g:HolmesHinchliffe:Swedish` in `hh.bib` resolves to HTTP 404. Replacing `print` with `books` seems to do the right thing, i.e. https://books.google.de/books?id=U8IxYGujF-8C does work.

### LINKED ISSUE #516: The  genealogical affiliation of Kafire (Senufo)
Dear all,

I am writing to tell about the  genealogical affiliation of Kafire. I was surprised to see that in Glottolog, **Kafire** (code **Kafire 1243**) is a dialect (child in the hierarchy) of **Cebaara Senufo**, whose motivation I do not know. In reality, in the literature (for instance Mensah and Tchagbale, 1983), Kafire and Cebaara are sisters since they are variants of Senari, a Senufo language spoken in the northen Côte d'Ivoire. Senari is known to have about **20 variants** including Kafire, Cebaara, Kufuru, Tangara etc. But it seems that you are using **Cebaara Senufo** as a synonym of Senari, which I do not know why. It is true that Cebaara is well documented and also serves as a kind of lingua franca as it was the language of the Senufo rulers of the region of Korhogo during the colonial period, but still it is a variant of Senari like the other variants. 

Regarding Kafire as such, I worked on it for my masters and I am preparing a PhD on it. It is spoken in three big villages, namely Sirasso, Nafoun and Kanoroba and their subordinate villages (more than 25 villages). So the region is big enough and is usually called the "Kafigue" (The region of the Kafibélé, the speakers of Kafire). These are the coordinates of the three big villages :

**Sirasso** 

Latitude: 9.276686
Longitude: -6.098986

**Nafoun** 

Latitude: 9.334722
Longitude: -6.211667

**Kanoroba**

Latitude: 9.110875
Longitude: -6.122378

Thanks.

### PR DESCRIPTION
**Pull request by d97hah**
…c dialect fixes + new hh.bib

- closes #516
- closes #515 
- closes #514

### CODE REVIEW

**Comment by xrotwang** [comment]
The big number of changed files, where dplace refs are removed, is due to dplace refs now being merged with hh.bib entries, and the language relations from these taking precedence.

**Comment by xflr6** [comment]
To double check: removal of ~5,000 `glottolog_ref_id`s from `hh.bib` is expected/intended?

**Comment by xrotwang** [comment]
oh. That's bad, I think. @d97hah did you maybe not pull the `glottolog_ref_id`s from release 4.2.1?
Thanks @xflr6 for catching that!

**Comment by xrotwang** [comment]
We could probably try to merge the `glottolog_ref_id` from v4.2.1 based on bibtex key.

**Comment by xrotwang** [comment]
@xflr6 would you like to have a go at this?

**Comment by d97hah** [comment]
I've made further changes to hh.bib so best I grab the reference id:s into
hh.bib from 4.2.1. Later this afternoon

Pada tanggal Sel, 12 Mei 2020 pukul 10.03 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
ok. Alternatively, you could just make a PR with your current hh.bib and we'll fix before merging.

**Comment by d97hah** [comment]
I did, see new PR, because I make changes to hh.bib around the clock and
don't want to wait for you :-)

Pada tanggal Sel, 12 Mei 2020 pukul 11.54 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
I see. So basically, no one except you can touch `hh.bib`, right? Then you may want to re-introduce the URL fixes I did earlier https://github.com/glottolog/glottolog/pull/517/commits/63dde6ea13d85eae18093d5d127cd7cb9d018ec5 :)

**Comment by d97hah** [comment]
Thanks fixed them. Normally I respect others changes in hh.bib as long as I
am aware of them, and there seems to be som lack of awareness of that on my
part, thanks for the overt note :-)

Pada tanggal Sel, 12 Mei 2020 pukul 16.42 Robert Forkel <
notifications@github.com> menulis:

**Comment by xflr6** [comment]
Thanks, see also https://github.com/glottolog/glottolog/pull/518#issuecomment-627415479

**Comment by d97hah** [comment]
Thanks those ref_id additions should be there in hh.bib because those refs
(added yesterday) are identical to items already in eball and thus already
have a ref_id. Thx for noticing though. all the best, H

Pada tanggal Sel, 12 Mei 2020 pukul 17.27 Sebastian Bank <
notifications@github.com> menulis:

**Comment by xflr6** [comment]
Sounds good, thanks for checking Harald (should we add back the encoding header)?

**Comment by d97hah** [comment]
It does no damage there and ensures the file is opened correctly on some
versions/settings of Emacs on Windows, where I used to have problems.
Nevermind it and I'll insert if needed.

Pada tanggal Sel, 12 Mei 2020 pukul 17.48 Sebastian Bank <
notifications@github.com> menulis:

**Pull request merged**
