### PR TITLE
drop empty altnames sections

### PR DESCRIPTION
**Pull request by xflr6**
via `treedb` roundtrip

### CODE REVIEW

**Comment by xrotwang** [comment]
First thing I'll merge **after** v4.5 :) Ok?

**Comment by xflr6** [comment]
SGTM (maybe next time provide a deadline for the PR) :)

**Comment by xrotwang** [comment]
True. I should learn to run treedb roundtrip, too. Could you add the relevant command to the release instructions?

**Comment by xflr6** [comment]
SG, will do (it's basically `treedb.load()` and `treedb.write_files()`).

I will need to put an `xfail` for this version into `treedb`:

https://github.com/glottolog/treedb/runs/4482250979?check_suite_focus=true

```python
E           AssertionError: checksum(**{'source': 'files', 'limit': 100}) == checksum(**{'source': 'raw', 'order_by': 'file', 'limit': 100})
E           assert '38aee32143a8...6a0372482d63a' == 'd87ffad4fc4d...8cb0bcbf846e8'
E             - d87ffad4fc4d6b3fd0d84151088a0f0137d7b81c7caf50f651b8cb0bcbf846e8
E             + 38aee32143a8823f7e0ecc25ac6d594fe7316e1d1c5ec88fd946a0372482d63a
```

https://github.com/glottolog/treedb/blob/f61c868774e8469f9583d6a20ad73f24722a95e8/tests/reads_repo/test_export_reads.py#L231-L235

**Comment by xflr6** [comment]
Xfail added in https://github.com/glottolog/treedb/commit/9955bd4e125954e228887b42645813119f1e8a1f

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
