### PR TITLE
[ojib1241] Update md.ini for ISO639-1/2/3 [oj/oji]

### PR DESCRIPTION
**Pull request by verdy-p**
this "family" is described in ISO 639-3 as a "macrolanguage", is also present in ISO 639-2, and has ISO639-1 code "oj".

### CODE REVIEW

**Comment by d97hah** [comment]
Macrolanguage is not a category realized by Glottolog. all the best, H

Pada tanggal Sab, 10 Okt 2020 pukul 02.49 Philippe Verdy <
notifications@github.com> menulis:

**Comment by verdy-p** [comment]
Once again you are wrong. Yes the term macroloanguage comes from ISO 639,
where as Glottolog speaks about langoids for all levels (superfamilies,
families, subfamilies, macrolanguages, languages, regional dialects or
dialects for some usages...
Lot of macrolanguages are in Glottolog, notably Chinese Mandarin for the
largest one, but we could say the same thing about (macro-)English and
(macro-)French !

It seems that each time those exclusions are not really justified by any
real policy but that you invent the policy on an ad hoc basis, just to
reduce the scope of the work that needs to be done and that you can't do
for now, or because you are not competent enough to treat some languages or
because of some political bias. I wonder who is really driving Glottolog
and if it really has a community (as stated).

At least ISO has a committee and its decisions are policies are justified
(even if you don't like their decision). But further votes can change
things and the reasons are made public (not the case with Glottolog that do
not give their reasons). It does not seem to be the case for Glottolog
which now just seems to me that it follows a private strategy that no one
can discuss or contest.

**Comment by xrotwang** [comment]
@verdy-p "not realized in Glottolog" above means we don't have a concept "macrolanguage" in Glottolog - hence `macrolanguage` is an invalid value for `level` in a languid's info file. That doesn't mean that Glottolog does not contain any entities which are categorized as macrolanguage elsewhere. It only means Glottolog does not have a stance on what a macrolanguage is, and neither does processing software relying o Glottolog.

We appreciate feedback and acknowledge that Glottolog should have more accessible or transparent policies. Possibly that's due to Glottolog not having a committee. Out of your conjectured reasons for our intransparence, I'd pick laziness over incompetence or bias. But maybe you mistook us for a bigger organization than we are.

**Comment by verdy-p** [comment]
I think that given you are trying to collect info and relevant links about
languages, not tracking the status given by ISO (or IANA for BCP 47) is
something that should be added.
There are multiple organizations trying to organize this, including The
Linguist List, and important resources like online dictionaries.
It seems you have chosen (but not explained) to concentrate only on L1
languages, even those that are "extinct" (but only in L1 usage), and
displaying "extinct" only is misleading your readers.
As well the classification as L1 is insufficient, given that L2 languages
are also very important for effective intercommunity usage (which is often
more prevalent than L1 only, especially for lot of minority languages that
are not written with any attested orthography, when in fact a language can
still exist and be active as L2 in written form and perfectly usable and
more and more used in this form, even if that written form (e.g. "zh")
encompasses many spoken languages (the written form can be read
differently, it does not necessarily represent the actual phonology. Other
examples are sign languages (which are partly encoding a language, but
almost always used as a secondary minority language in combination with
another major L1 language in a mixed usage with gestual signs added to
represent its orthography or phonology).
So there are severe limitations in Glottolog, and they are not
explained/justified at all.
The way I read your personal statements, they all appear to be "adhoc" and
expeditive.
"Lazyness" is not a good excuse, we can accept that this cannot be
complete, but refusing to add relevant data that woul be really helpful
(and still easy to assert), seems to be a bad decision (which is in fact in
contradiction with your own existing goals stated on your main website). I
do not expect any such database to be complete, but rejecting additions
like what is done now, means that your "collaborative" efforts (affirmed by
your website) is in fact false ad nyour just want to publish personal works
and this means that Glottolog is not reliable and we should then work with
other groups whose work is more really collaborative and more trustable
(e.g. The Linguist List, or ISO, or CLDR, even if it's not possible to
decide there to satisfy everyone, there should exist a place in Glottolog
for proposals that need later research works and vetting, even if you have
still not endorsed these additions yourself). Not doing tht means that it's
impossible to get a path to build a convergence and consensus with other
groups: Glottolog want to work alone with limited resources that cannot
reach the goals it is supposed to reach, and Glottolog is then not an
"open" project even if its data are in an opendata repository: its work is
unidirectional, we can use it "as is", but with evident risks of being
misguided. And Glottlog is not at all a reliable source, as it is now
proven it is biased and uncorrectable.

Le dim. 11 oct. 2020 à 07:44, Robert Forkel <notifications@github.com> a
écrit :

**Comment by xrotwang** [comment]
I tried to explain why we won't accept the `level = macrolanguage` line in your PR. Most of the remaining data you provided for Ojibwa could technically be added to Glottolog (in the sense that it would not trip up any processing software). Note, though, that we link ISO 639-3 macrolanguages only (and this is discovered automatically) if these have the same extension (set of child languages) as a corresponding Glottolog languoid. So if any of ISO 639-3's Ojibwa child languages isn't linked from a Glottolog child language of Ojibwa, we don't make this link. (Sorry that this is not explained anywhere.)

You will see, though, that languoids on the `family` level have almost no information in Glottolog - other than the position in the language classification. This is because Glottolog focuses on L1 languages (and a classification of these) - not on collecting as much information as possible on each level of the tree (again sorry if this isn't clearly documented). So I'd be hesitant to start adding such information since this may lead to an expectation in terms of completeness that we'll never be able to fulfill.

We accept that Glottolog is severly limited in several ways, but it has its uses **and** users (and even contributors) - even though we didn't manage to exhaustively document what these are. If you have a hard time accepting the choices Glottolog makes, and feel these choices make it unusable fo you, maybe it is not for you - and as you say, there may be alternatives available. You may even fork this repository and try to start a more open/correct/useful variant of Glottolog - although this would not be our prefered solution.

**Pull request closed without merging**
