### PR TITLE
Release 4.7 bis

### PR DESCRIPTION
**Pull request by xrotwang**

### CODE REVIEW

**Comment by xrotwang** [comment]
@xflr6 This is basically #908 on top of what wals `release-4.7` before. Feel free to check if you find the time - but if not, I'll release anyway later today, risking the bug-fix release :)

**Comment by xflr6** [comment]
Thanks  Robert, sent #911 to re-apply #905.

**Comment by xflr6** [comment]
Values diff:

```diff
-      "core                   name                   26,285\n",
-      "core                   hid                    8,858\n",
-      "core                   level                  26,285\n",
-      "core                   iso639-3               8,130\n",
-      "core                   latitude               8,755\n",
-      "core                   longitude              8,755\n",
-      "core                   macroareas             21,616\n",
-      "core                   countries              11,463\n",
+      "core                   name                   26,416\n",
+      "core                   hid                    8,864\n",
+      "core                   level                  26,416\n",
+      "core                   iso639-3               8,129\n",
+      "core                   latitude               8,763\n",
+      "core                   longitude              8,763\n",
+      "core                   macroareas             21,709\n",
+      "core                   countries              11,468\n",
       "core                   name_comment           14\n",
       "core                   comment                1\n",
       "core                   location               1\n",
       "core                   name_pronunciation     1\n",
       "core                   speakers               1\n",
-      "core                   links                  29,722\n",
-      "core                   timespan               199\n",
-      "sources                glottolog              197,791\n",
-      "altnames               multitree              54,501\n",
-      "altnames               hhbib_lgcode           34,996\n",
+      "core                   links                  27,574\n",
+      "core                   timespan               634\n",
+      "sources                glottolog              198,801\n",
+      "altnames               multitree              54,493\n",
+      "altnames               hhbib_lgcode           35,719\n",
       "altnames               lexvo                  26,027\n",
-      "altnames               elcat                  24,422\n",
-      "altnames               aiatsis                6,542\n",
-      "altnames               wals                   2,442\n",
+      "altnames               elcat                  24,438\n",
+      "altnames               aiatsis                6,588\n",
+      "altnames               wals                   2,441\n",
       "altnames               wals other             2,097\n",
-      "altnames               moseley & asher (1994) 2,089\n",
+      "altnames               moseley & asher (1994) 2,088\n",
       "altnames               ruhlen (1987)          2,007\n",
-      "altnames               glottolog              1,742\n",
+      "altnames               glottolog              1,794\n",
       "altnames               ethnologue             3\n",
-      "triggers               lgcode                 30,071\n",
+      "triggers               lgcode                 29,988\n",
       "triggers               inlg                   187\n",
-      "identifier             multitree              14,849\n",
-      "identifier             endangeredlanguages    3,596\n",
-      "identifier             wals                   2,620\n",
-      "identifier             languagelandscape      337\n",
-      "classification         sub                    11,816\n",
-      "classification         subrefs                16,613\n",
-      "classification         family                 210\n",
-      "classification         familyrefs             708\n",
-      "endangerment           status                 8,345\n",
-      "endangerment           source                 8,345\n",
-      "endangerment           date                   8,345\n",
-      "endangerment           comment                8,345\n",
+      "identifier             multitree              14,841\n",
+      "identifier             endangeredlanguages    3,600\n",
+      "identifier             wals                   2,618\n",
+      "identifier             languagelandscape      334\n",
+      "classification         sub                    11,864\n",
+      "classification         subrefs                16,859\n",
+      "classification         family                 187\n",
+      "classification         familyrefs             685\n",
+      "endangerment           status                 8,353\n",
+      "endangerment           source                 8,353\n",
+      "endangerment           date                   8,353\n",
+      "endangerment           comment                8,353\n",
       "hh_ethnologue_comment  isohid                 613\n",
       "hh_ethnologue_comment  comment_type           613\n",
       "hh_ethnologue_comment  ethnologue_versions    613\n",
       "iso_retirement         change_to              451\n",
       "iso_retirement         remedy                 327\n",
       "iso_retirement         comment                232\n",
```

**Comment by xflr6** [comment]
Languoids diff:

```diff
-      "26,285 languoids\n",
+      "26,416 languoids\n",
       "   245 families\n",
-      "   182 isolates\n",
-      "   427 roots\n",
-      " 8,565 languages\n",
-      " 4,388 subfamilies\n",
-      "13,087 dialects\n",
-      " 7,628 Spoken L1 Languages\n",
+      "   184 isolates\n",
+      "   429 roots\n",
+      " 8,572 languages\n",
+      " 4,425 subfamilies\n",
+      "13,174 dialects\n",
+      " 7,636 Spoken L1 Languages\n",
       "   215 Sign Language\n",
       "   121 Unclassifiable\n",
       "    84 Pidgin\n",
       "    68 Unattested\n",
       "    32 Artificial Language\n",
-      "    10 Mixed Language\n",
+      "     9 Mixed Language\n",
       "    15 Speech Register\n"
```

**Pull request merged**
