### PR TITLE
Updated hh bib and delted duplicate in asjp 2000

### PR DESCRIPTION
**Pull request by HedvigS**
Wrong inlang for a reference and duplicate references.

I don't know if this is the way to do this, trying it out.

### CODE REVIEW

**Comment by xrotwang** [comment]
`hh.bib` is @d97hah 's bib, so I'd see this PR as a way to recommend a certain change to Harald. The ASJP bib otoh is basically read-only - its the bibliography of the ASJP project and removing an entry from it would only be justified if that item referenced by the entry wasn't actually used to compile the ASJP data. AFAIKT that's not what you are suggesting, right?

Generally, duplicates **across** different bibtex files in glottolog are not a problem - rather a feature. Merging of records only takes place when the database for the web app is compiled.

**Comment by HedvigS** [comment]
Right, so how should one go about filing changes that result in a change in the compilation of data for the web app?

**Comment by xrotwang** [comment]
AFAIKT you want to get rid of a duplicate here, right? The way to do this is by making sure the merge mechanism will identify the two entries in `hh.bib` and `asjp.bib`. This merge algorithm looks at title, author and year (mainly), so as soon as Harald accepts the spanish title for the entry in `hh.bib`, we should be good.

**Comment by HedvigS** [comment]
Yes, removing duplicate, having both German and Spanish titles in title and inlang = Spanish [spa] was the aim. Standardising the name would also be ideal for these two references.

**Comment by d97hah** [comment]
I've adjusted the name of the author which will enable the merge of the
ASJP/HH versions in the next edition and I've adjusted hh.bib accordingly.
Thanks, H

Pada tanggal Sen, 30 Mar 2020 pukul 19.23 Robert Forkel <
notifications@github.com> menulis:

**Pull request closed without merging**
