### PR TITLE
Change add Wikipedia and Wikidata links to Primitive Irish and Faeto and Celle San Vito Francoprovencal entries

### PR DESCRIPTION
**Pull request by Arctic-Circle-System**

### CODE REVIEW

**Comment by d97hah** [comment]
Why change the name? Faetar is just one of the two places where the lg is spoken. In any case, don't change codes along with changing names, that's the point of codes as separate from names.

**Comment by Arctic-Circle-System** [comment]
Would changing it to "Faetar-Cigliàje" work, then? "Faeto and Celle San Vito Francoprovencal" is a bit long, though if it needs to be left as-is then I'll just revert that part of the request.

**Comment by d97hah** [comment]
That would work I guess but I don't see the problem with a long name if the
underlying place has a long name. There's enough space on the internet and
one can abbreviate as needed.

Pada Sel, 14 Nov 2023 pukul 21.51 Arctic Circle System <
***@***.***> menulis:

**Comment by Arctic-Circle-System** [comment]
That's true. I'll revert that commit then.

**Pull request merged**
