### PR TITLE
Added Wikimedia links to various Nuclear Trans New Guinea entries, moved and removed erronerously assigned Wikipedia links, fixed typos, fixed minor inconsistency

### PR DESCRIPTION
**Pull request by Arctic-Circle-System**

### CODE REVIEW

**Comment by xrotwang** [comment]
Thanks for your effort! We'll have to review the way we curate the wikipedia links at the moment, I guess. Currently, they are harvested automatically, see https://github.com/glottolog/pyglottolog/blob/master/src/pyglottolog/links/wikidata.py
So essentially, links between Glottolog and Wikipedia are curated on the Wikipedia side, and harvested by us. This means - unless the same changes happen on Wikipedia - your changes here will be lost with the next automatic update of links.

Alternatively, if you happen to also be a Wikipedia editor, you could try to add the links to Glottolog there. Then they'd land here automatically at some point.

**Comment by Arctic-Circle-System** [comment]
I do believe that a lot of the Wikipedia pages I added links for have Glottolog links on them, though I do need to go through some of the Wikidata links and add the links to those. Part of the issue is that some articles on Wikipedia related to closely related dialects, languages, etc have certain topics combined together whether it's warranted or not. It gets particularly dire when looking at articles on languages that aren't well-known and are closely related to other languages or whose phylogenetic classification is contested.

**Comment by d97hah** [comment]
I am not to happy about the suggested name changes. Minjim is the spelling
Don Daniels used for the subgroup. Bipartite names like
Kalam-Kobon are preferrable if not too long and there is no strive towards
consistency across levels anyway. all the best, H

Pada Sab, 18 Nov 2023 pukul 11.04 Arctic Circle System <
***@***.***> menulis:

**Comment by Arctic-Circle-System** [comment]
Alright, I'll close the pull request.

**Pull request closed without merging**
