### PR TITLE
More arawakan updates + Miltu reclf

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Review by xrotwang — COMMENTED** [review]
I see you are removing a language level languoid:
https://github.com/glottolog/glottolog/pull/550/files#diff-f817b40756edef86e353d4a879b5f78b

Is this intended?

**Comment by d97hah** [comment]
No not intended, the only lg-level languoids that got removed (as opposed to demoted to dialect) can think of in the PR is Marawan, now fixed. Is there an easy way to check if trhere were more?

**Comment by xrotwang** [comment]
I read through the whole diff :) and no, there are no more.

**Review by xrotwang — CHANGES_REQUESTED** [review]
There's still something wrong. This is what `glottolog-admin check` tells me:
```
ERROR   NOCODE_Maipure: duplicate hid
languoids/tree/araw1281/alto1249/maip1247/maip1246
languoids/tree/araw1281/alto1249/maip1247
ERROR   inp: duplicate hid
languoids/tree/araw1281/sout3131/puru1269/puru1265/inap1242
languoids/tree/araw1281/sout3131/puru1269/puru1265/inap1242/inap1243
ERROR   szn: duplicate hid
languoids/tree/aust1307/mala1545/cent2237/cent2245/cent2254/west2817/buru1321/sula1247/sula1248/sula1245
languoids/tree/aust1307/mala1545/cent2237/cent2245/cent2254/west2817/buru1321/sula1247/sula1248
```

It looks like you didn't start out with the old tree again?

Let me know, if I should fix.

**Comment by xrotwang** [comment]
Ah, no. It looks as if the dialect-level languoids should not have kept the `hid` - right?

**Comment by d97hah** [comment]
lff2tree does not remove hid:s from the md.ini:s (but it does add them), I
may have mentioned this before and/or I am not using the latest version of
glottolog / glottolog-admin because my glottolog check fails before this
test on the hh_iso_comment issue. For now the easiest fix is to remove the
association from the lower node in all cases.

Pada tanggal Rab, 19 Agu 2020 pukul 15.28 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
ok, I'll do.

**Comment by d97hah** [comment]
Right

Pada tanggal Rab, 19 Agu 2020 pukul 15.31 Robert Forkel <
notifications@github.com> menulis:

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
